### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument '__no_builder'

### ISSUE THREAD

**Issue by FourierSignal** [hackebrot/daumenkivy#1]
python main.py  

Traceback (most recent call last):
   File "main.py", line 10, in <module>
     DaumenkivyApp().run()
   File "/Users/durgasunil/.pyenv/versions/3.8.0/lib/python3.8/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/Users/durgasunil/.pyenv/versions/3.8.0/lib/python3.8/site-packages/kivy/app.py", line 918, in _run_prepare
     self.load_kv(filename=self.kv_file)
   File "/Users/durgasunil/.pyenv/versions/3.8.0/lib/python3.8/site-packages/kivy/app.py", line 691, in load_kv
     root = Builder.load_file(rfilename)
   File "/Users/durgasunil/.pyenv/versions/3.8.0/lib/python3.8/site-packages/kivy/lang/builder.py", line 306, in load_file
     return self.load_string(data, **kwargs)
   File "/Users/durgasunil/.pyenv/versions/3.8.0/lib/python3.8/site-packages/kivy/lang/builder.py", line 404, in load_string
     widget = Factory.get(parser.root.name)(__no_builder=True)
 TypeError: __init__() got an unexpected keyword argument '__no_builder'
bash-3.2$

**Comment by hackebrot** [comment]
Hi @FourierSignal! 👋🏻 

This project hasn't been updated in the last 7 years and does not support newer Python 3 versions.

I will mark this repository as archived and read-only now.
